package com.mak001.ircbot.api.listeners;

import com.mak001.ircbot.irc.Server;
import com.mak001.ircbot.irc.plugin.Listener;

/**
 * Listens for Actions performed in a channel or private message.
 * 
 * @author MAK001
 */
public interface ActionListener extends Listener {

	/**
	 * This method is called whenever an ACTION is sent from a user. E.g. such
	 * events generated by typing "/me goes shopping" in most IRC clients.
	 * <p/>
	 * The implementation of this method in the PircBot abstract class performs
	 * no actions and may be overridden as required.
	 * 
	 * @param sender
	 *            The nick of the user that sent the action.
	 * @param login
	 *            The login of the user that sent the action.
	 * @param hostname
	 *            The hostname of the user that sent the action.
	 * @param target
	 *            The target of the action, be it a channel or our nick.
	 * @param action
	 *            The action carried out by the user.
	 */
	public void onAction(Server server, String sender, String login, String hostname,
			String target, String action);

}
